### ISSUE TITLE
Enhance and Standardize CONTRIBUTING.md

### ISSUE THREAD

**Issue by HimanshuMahto** [oshi/oshi-ffm#53]
In this issue, we aim to enhance and standardize the content of the `CONTRIBUTING.md` file within the project repository. The current `CONTRIBUTING.md` file contains valuable information for potential contributors but needs improvement to make it more informative and user-friendly.

Key tasks for this issue include:
- Reviewing the existing content to ensure clarity and completeness.
- Adding sections that explain the project's code of conduct, code formatting guidelines, and developer certificate of origin (DCO).
- Formatting the document to be more reader-friendly, with clear headings and organized sections.
- Ensuring that contributors understand the licensing requirements and best practices when submitting code.

The objective is to provide a comprehensive and accessible guide for community members who wish to contribute to the project. The improved `CONTRIBUTING.md` will support a welcoming and collaborative environment for contributors, promoting the growth and success of the OSHI-FFM project.

If you like the idea please do assign me this to work on. @hazendaz @mprins @dbwiddis @ronan696

**Comment by dbwiddis** [comment]
Hey @HimanshuMahto, thanks for your interest. This issue seems somewhat boilerplate.

Given very little participation on this repo over the last year we're probably going to move the code from here to the main repo, so it's unlikely that improving the docs here will do much.
